pipeline:
  deploy:
    image: glaszi/drone-capistrano
    tasks: production deploy
    secrets:
      - api_bucket_key
      - api_bucket_secret
    when:
      branch: master
      event: push
  #  build:
  #  image: ruby:2.5.1
  #  commands:
  #    - bundle install
  #    - cap production deploy
  #  when:
  #    branch: master
  #    event: push
  #  secret: [api_bucket_key, api_bucket_secret]
